#!/usr/bin/env bash

rm -rf target

archs=(
    x86_64-unknown-linux-gnu \
    x86_64-pc-windows-msvc \
    x86_64-apple-darwin \
    aarch64-apple-darwin
)

for arch in ${archs[@]}; do
    ARCH=$arch deno task -q compile
done
